import './lib/jsbezier@0.9.4/jsbezier.js'
import './lib/biltong@0.4.0/biltong.js'
import './lib/mottle@1.0.0/mottle.js'
import './lib/katavorio@1.4.8/katavorio.js'

import './lib/jsplumb@2.10.2/util.js'
import './lib/jsplumb@2.10.2/browser-util.js'
import './lib/jsplumb@2.10.2/lists.js'
import './lib/jsplumb@2.10.2/jsplumb.js.js'
import './lib/jsplumb@2.10.2/overlay-component.js'
import './lib/jsplumb@2.10.2/endpoint.js'
import './lib/jsplumb@2.10.2/connection.js'
import './lib/jsplumb@2.10.2/anchors.js.js'
import './lib/jsplumb@2.10.2/defaults.js'
import './lib/jsplumb@2.10.2/group.js'
